# Temporary container for building dependancies
FROM debian:buster AS builder
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
       ca-certificates \
       build-essential \
       libcap-dev \
       libsystemd-dev \
       pkg-config \
       git \
    && rm -rf /var/lib/apt/lists/*


# Compile isolate for safe code execution
FROM builder AS isolate
RUN git clone https://github.com/ioi/isolate.git
WORKDIR /isolate
RUN git checkout -b build v2.1
RUN make isolate
RUN make isolate-cg-keeper


# Compile isolock wrapper for isolate
FROM builder AS isolock
RUN git clone https://github.com/ronalchn/isolock.git
WORKDIR /isolock
RUN make


# Ruby application
FROM ruby:2.4.10 AS nztrain
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
       libmaxminddb-dev \
       build-essential \
    && rm -rf /var/lib/apt/lists/*
COPY ./nztrain /app
WORKDIR /app
RUN bundle install -j4
COPY ./config/database.yml ./config/redis.yml ./config/isolate.yml /app/config/
COPY ./config/isolate.cf /usr/local/etc/isolate
COPY --from=isolate /isolate/isolate /isolate/isolate-check-environment /usr/local/bin/
COPY --from=isolate /isolate/isolate-cg-keeper /usr/local/sbin/
COPY --from=isolock /isolock/bin/isolock /usr/local/bin/isolock


CMD ["/bin/bash"]
